<a href="https://colab.research.google.com/github/FatherOfLove/258_DL/blob/master/Array_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

nums = [
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120],
    [130, 140, 150, 160]
]
print("Original List:",nums)
result = []
for sublist in nums:
    for item in sublist:
        result.append(item)
print("\nCollapse nested lists:")
print(result)

Original List: [[10, 20, 30, 40], [50, 60, 70, 80], [90, 100, 110, 120], [130, 140, 150, 160]]

Collapse nested lists:
[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160]


In [2]:
import array as arr 
  
# creating an array with integer type 
a = arr.array('i', [1, 2, 3]) 
  
# printing original array 
print ("The new created array is : ", end =" ") 
for i in range (0, 3): 
    print (a[i], end =" ") 
print() 
  
# creating an array with float type 
b = arr.array('d', [2.5, 3.2, 3.3]) 
  
# printing original array 
print ("The new created array is : ", end =" ") 
for i in range (0, 3): 
    print (b[i], end =" ") 

The new created array is :  1 2 3 
The new created array is :  2.5 3.2 3.3 

In [3]:
a = arr.array('i', [1, 2, 3]) 
  
  
print ("Array before insertion : ", end =" ") 
for i in range (0, 3): 
    print (a[i], end =" ") 
print() 
  
# inserting array using  
# insert() function 
a.insert(1, 4) 
  
print ("Array after insertion : ", end =" ") 
for i in (a): 
    print (i, end =" ") 
print()  
  
# array with float type 
b = arr.array('d', [2.5, 3.2, 3.3]) 
  
print ("Array before insertion : ", end =" ") 
for i in range (0, 3): 
    print (b[i], end =" ") 
print() 
  
# adding an element using append() 
b.append(4.4) 
  
print ("Array after insertion : ", end =" ") 
for i in (b): 
    print (i, end =" ") 
print()  

Array before insertion :  1 2 3 
Array after insertion :  1 4 2 3 
Array before insertion :  2.5 3.2 3.3 
Array after insertion :  2.5 3.2 3.3 4.4 


In [4]:
a = arr.array('i', [1, 2, 3, 4, 5, 6]) 
  
# accessing element of array 
print("Access element is: ", a[0]) 
  
# accessing element of array 
print("Access element is: ", a[3]) 
  
# array with float type 
b = arr.array('d', [2.5, 3.2, 3.3]) 
  
# accessing element of array 
print("Access element is: ", b[1]) 
  
# accessing element of array 
print("Access element is: ", b[2]) 

Access element is:  1
Access element is:  4
Access element is:  3.2
Access element is:  3.3


In [5]:
import array 
   
# initializing array with array values 
# initializes array with signed integers 
arr = array.array('i', [1, 2, 3, 1, 5])  
  
# printing original array 
print ("The new created array is : ", end ="") 
for i in range (0, 5): 
    print (arr[i], end =" ") 
  
print ("\r") 
  
# using pop() to remove element at 2nd position 
print ("The popped element is : ", end ="") 
print (arr.pop(2)) 
  
# printing array after popping 
print ("The array after popping is : ", end ="") 
for i in range (0, 4): 
    print (arr[i], end =" ") 
  
print("\r") 
  
# using remove() to remove 1st occurrence of 1 
arr.remove(1) 
  
# printing array after removing 
print ("The array after removing is : ", end ="") 
for i in range (0, 3): 
    print (arr[i], end =" ") 

The new created array is : 1 2 3 1 5 
The popped element is : 3
The array after popping is : 1 2 1 5 
The array after removing is : 2 1 5 

In [0]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [7]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [8]:
x1

array([5, 0, 3, 3, 7, 9])

In [9]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [10]:
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])